# Generated by Django 5.0.4 on 2024-05-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='test2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
